CREATE TABLE CITY(
	CID INTEGER PRIMARY KEY NOT NULL,
	C_NAME TEXT NOT NULL
);

CREATE TABLE WEATHER(
	WDATE TEXT PRIMARY KEY,
	C_ID TEXT NOT NULL,
	WSTATE TEXT NOT NULL,
    TEMP REAL,

	FOREIGN KEY (C_ID) REFERENCES CITY(ID)
);